language: node_js

node_js:
  - "0.10.12"

before_script:
  - npm install -g mocha
  - npm install -g bower
  - npm install
  - bower install
  - node app.js &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - mocha
  - './node_modules/.bin/karma start --single-run --browsers PhantomJS'
